### ISSUE TITLE
I couldn't open the Crunchyroll Downloader.exe by double clicking it.

### ISSUE THREAD

**Issue by YFTX2015** [hama3254/experimental-Crunchyroll-Downloader-v3.x#1]
**Describe the bug**

**Where does the issue happen?**
 - Platform: [e.g. Crunchyroll Beta, Cruchyroll Classic, Funimation]
 - Settings [e.g. Hardsubs, Softsubs, ffmpeg options]
 - Version [e.g. v3.8.7.2]

**Screenshots**

**Additional context**

**Comment by hama3254** [comment]
if you are refering to the `Crunchyroll Downloader.exe` inside this repository then you just got a (replacement) part of the full package which can be found [here as Crunchyroll-Downloader-v3.9_portable_4.zip](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/releases/tag/v3.9-Portable)
